In [2]:
import pandas as pd

In [3]:
df_c = pd.read_csv('../Data/covid_us_ext.csv')
df_c_C= df_c[(df_c['Country/Region'] == 'Mainland China')].iloc[:, :6]
#df_c_US = df_c.drop(df_c_C.index, axis =0)
df_c_US = df_c[(df_c['Country/Region'] == 'US')]
df_c_US['ObservationDate'] = pd.to_datetime(df_c_US['ObservationDate'],dayfirst=True,format='%m/%d/%Y')
df_c_US.sort_values('ObservationDate')

<ipython-input-3-cbf69ba9a8ed>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_c_US['ObservationDate'] = pd.to_datetime(df_c_US['ObservationDate'],dayfirst=True,format='%m/%d/%Y')

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
31,32,2020-01-22,Washington,US,1/22/2020 17:00,1.0,0.0,0.0
70,71,2020-01-23,Washington,US,1/23/20 17:00,1.0,0.0,0.0
119,120,2020-01-24,Washington,US,1/24/20 17:00,1.0,0.0,0.0
120,121,2020-01-24,Chicago,US,1/24/20 17:00,1.0,0.0,0.0
161,162,2020-01-25,Washington,US,1/25/20 17:00,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
285013,285014,2021-05-02,Maryland,US,2021-05-03 04:20:39,448989.0,8776.0,0.0
285014,285015,2021-05-02,Massachusetts,US,2021-05-03 04:20:39,691172.0,17621.0,0.0
285025,285026,2021-05-02,Michigan,US,2021-05-03 04:20:39,940175.0,18893.0,0.0
284878,284879,2021-05-02,Grand Princess,US,2021-05-03 04:20:39,103.0,3.0,0.0
285289,285290,2021-05-02,Wyoming,US,2021-05-03 04:20:39,58142.0,707.0,0.0

In [4]:
df_c_US = df_c_US.groupby(['ObservationDate']).sum().reset_index()#.sort_values('ObservationDate')
df_c_US = df_c_US.drop(columns=['SNo','Deaths','Recovered'])

df_c_US

    ObservationDate   Confirmed
0        2020-01-22         1.0
1        2020-01-23         1.0
2        2020-01-24         2.0
3        2020-01-25         2.0
4        2020-01-26         5.0
..              ...         ...
462      2021-04-28  32230850.0
463      2021-04-29  32289049.0
464      2021-04-30  32346971.0
465      2021-05-01  32392274.0
466      2021-05-02  32421534.0

[467 rows x 2 columns]

In [5]:
df_c_US.to_csv("../Data/Confirmed_Cases_US.csv")

In [6]:
df =  pd.read_csv('../Data/Confirmed_Cases_US.csv')
df=df.drop(columns=['Unnamed: 0'])
df.columns

Index(['ObservationDate', 'Confirmed'], dtype='object')